
name: checkout workflow

on: [ workflow_dispatch ]

jobs:

    show-files:
        runs-on: ubuntu-latest

        steps:
            
            - name: checkout repo
              uses: actions/checkout@v5

            - name: show files
              run: ls -lsrth

            - name: display the content of the file
              run: cat f1.txt

          



            
