

name: shell script workflow

on: [ workflow_dispatch ]

jobs:
    shell-script:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v5

            - name: display file content
              run: cat f1.txt

            - name: giving execute permission
              run: chmod +x uptime.sh

            - name: execute the shell script
              run: ./uptime.sh


              